#!/bin/bash

#set -x

FOLDER_PATH="/vagrant/cloudooo_manager_buildout"
CLOUDOOO_OPTS=""

cloudoooctl_path="$FOLDER_PATH/bin"
pid_path="$FOLDER_PATH/run"

. /lib/lsb/init-functions

case "$1" in
  start)
     log_daemon_msg "Starting Cloudooo Manager server..." "cloudooomanager"
     if start-stop-daemon --start --quiet --oknodo --pidfile $pid_path/cloudooomanager.pid --exec \
        $cloudoooctl_path/cloudooomanager_ctl start $CLOUDOOO_OPTS; then
        log_end_msg 0
     else
        log_end_msg 1
     fi
     ;;

  stop)
     log_daemon_msg "Stoping Cloudooo Manager server..." "cloudooomanager"
     if start-stop-daemon --stop --quiet --oknodo --pidfile $pid_path/cloudooomanager.pid --exec $cloudoooctl_path/cloudooomanager_ctl stop; then
        $cloudoooctl_path/cloudooomanager_ctl stop
        log_end_msg 0
     else
        log_end_msg 1
     fi
     ;;

  status)
     status_of_proc -p $pid_path/cloudooomanager.pid $cloudoooctl_path/cloudooomanager_ctl cloudooomanager && exit 0 || exit $?
     ;;

  *)
    log_action_msg "Usage: /etc/init.d/cloudooomanager {start|stop|status}"
    exit 1
esac

exit 0
